targets:
  AU:
    Airfryer: 0
    All_in_One: 0
    FAEM: 0
    Handheld_Steamer: 0
  BR:
    Airfryer: 0
    Blender: 0
    FAEM: 0
  DE:
    Airfryer: 325
    FAEM: 325
    Handheld_Steamer: 325
    Handstick_Dry: 325
    Handstick_WD: 325
    RVC: 325
    SAEM: 325
  FR:
    Airfryer: 350
    FAEM: 350
    Handheld_Steamer: 350
    Handstick_Dry: 350
    RVC: 350
    SAEM: 350
  NL:
    Airfryer: 150
    FAEM: 150
    Handheld_Steamer: 150
    Handstick_Dry: 114
    Handstick_WD: 114
    RVC: 100
    SAEM: 150
  POL:
    Airfryer: 243
    FAEM: 243
    Handheld_Steamer: 218
    Handstick_Dry: 243
    Handstick_WD: 243
    RVC: 243
    SAEM: 243
    Stand_Steamer: 218
  TR:
    FAEM: 300
    Handheld_Steamer: 300
    Handstick_Dry: 300
    Handstick_WD: 300
    RVC: 300
    Steam_Generator: 300
    Steam_Iron: 300
  UK:
    Airfryer: 290
    FAEM: 290
    Handheld_Steamer: 250
    Handstick_Dry: 290
    Portioned_Espresso: 290
    SAEM: 290
  US:
    FAEM: 0
    SAEM: 0
